require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.alpha")
-- require("plugins.matchup")
require("plugins.blankline")
require("plugins.autopairs")
require("plugins.bullet")
require("plugins.markdown")
require("plugins.neoscroll")
require("plugins.oil")
require("plugins.telescope")
require("plugins.vague")
