require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.alpha")
require("plugins.blankline")
require("plugins.autopairs")
require("plugins.bullet")
require("plugins.markdown")
require("plugins.neoscroll")
require("plugins.oil")
require("plugins.telescope")
require("plugins.yazi")
require("plugins.surround")
require("plugins.gitsigns")
require("plugins.lualine")

-- themes
-- require("plugins.vague")
require("plugins.rose-pine")
