input {
    kb_layout = latam
    # kb_layout = es
    kb_options = caps:escape_shifted_capslock,menu:super
    follow_mouse = 1

    accel_profile = flat
    # accel_profile = custom 2 0.0 1.0 2.5 5.0 10.0
    accel_profile = custom 2 0.0 2.0 9.0
    # accel_profile = adaptive
    sensitivity = 0.0
    # sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification.
    numlock_by_default = true
    scroll_factor = 1.0   # default; increase to scroll faster, decrease to slow down

}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

device {
    name = wacom-one-by-wacom-s-pen
    output = HDMI-A-1
    transform = 4
    relative_input = false
    left_handed = true
}
